### ISSUE TITLE
Building TweakUtility Build 99 makes the language of the application go half-Spanish.

### ISSUE THREAD

**Issue by PF94** [Craftplacer/TweakUtility#24]
**Describe the bug**
The application is built in Spanish, You first don't notice it on the main window, but going to "About" shows spanish.

**To Reproduce**
1. Build the project on VS2017
2. Reload VS2017 because it asks me for admin
3. Rebuild the project
4. Open the project
5. Click on "Tweak Utility" to open the about prompt
6. See that it's in spanish.

**Expected behavior**
The about prompt should have been in English.

**Information (please complete the following information):**
 - OS: Windows 8.1
 - Version 1.0.99.30338

**Comment by Craftplacer** [comment]
I forced Tweak Utility to be Spanish so I could continue testing localization, but I commited because you really wanted my WIP code, the "bug" is located [here](https://github.com/Craftplacer/TweakUtility/blob/ec1a38ef0fa35094169ce47010c0c776bf8d43cc/TweakUtility/Program.cs#L131). 
This is here by, while I'm mainly working on 1.1 not a bug.
