### ISSUE TITLE
Exception error at Backups

### ISSUE THREAD

**Issue by AlienFuture** [Craftplacer/TweakUtility#36]
I've just wanted create a backup of my settings and I've got an unhandled exception
![screenshot of error](https://user-images.githubusercontent.com/42870867/63653090-96ada780-c768-11e9-8b73-fbb769cfc300.png)

Error log: https://pastebin.com/Bbh8DU2a

**Comment by Craftplacer** [comment]
Possibly fixed by [`474724b`](https://github.com/Craftplacer/TweakUtility/commit/474724b80996a65d2fcd3b18cc7c5e3f3e7404ac) and [`671a373`](https://github.com/Craftplacer/TweakUtility/commit/671a37360f6c96063c9ff3ce55f38e27d4d81eeb). Feel free to re-open this if this bug still occurs on the next release.
